puts("Enter a colour:")
colour = gets.chomp()
puts("Enter a plural noun:")
plural_noun = gets.chomp()
puts("Enter a celebrity:")
celebrity = gets.chomp()

puts("roses are " + colour)
puts(plural_noun + " are blue")
puts("I love " + celebrity)
